language: c
os:
    - linux
    - osx
compiler:
    - clang
    - gcc
env:
    # this global section can be removed when
    # https://github.com/travis-ci/travis-ci/issues/1844 is fixed
    # global:
    #     - CI=true
    #     - TRAVIS=true
    matrix:
        - TOX_ENV=py26
        - TOX_ENV=py27
        - TOX_ENV=py32
        - TOX_ENV=py33
        - TOX_ENV=py34
        - TOX_ENV=pypy
        - TOX_ENV=py26 OPENSSL=0.9.8
        - TOX_ENV=py27 OPENSSL=0.9.8
        - TOX_ENV=py32 OPENSSL=0.9.8
        - TOX_ENV=py33 OPENSSL=0.9.8
        - TOX_ENV=py34 OPENSSL=0.9.8
        - TOX_ENV=pypy OPENSSL=0.9.8
        - TOX_ENV=docs
        - TOX_ENV=pep8
        - TOX_ENV=py3pep8

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

after_success:
    - source ~/.venv/bin/activate && coveralls

notifications:
    irc:
        channels:
            - "irc.freenode.org#cryptography-dev"
        use_notice: true
        skip_join: true

# When building an exclude matrix on Travis you must supply the exact variable
# combinations you want to exclude from your build matrix. There is no
# (current) way to make this less verbose.
matrix:
    exclude:
        - os: osx
          compiler: gcc
        - os: osx
          env: TOX_ENV=pep8
          compiler: clang
        - os: osx
          env: TOX_ENV=py3pep8
          compiler: clang
        - os: linux
          env: TOX_ENV=docs
          compiler: clang
        - os: linux
          env: TOX_ENV=pep8
          compiler: clang
        - os: linux
          env: TOX_ENV=py3pep8
          compiler: clang
