sudo: false

language: python

cache:
    directories:
        - $HOME/.cache/pip

matrix:
    include:
        - python: 2.6 # these are just to make travis's UI a bit prettier
          env: TOXENV=py26
        - python: 2.7
          env: TOXENV=py27
        - python: 3.3
          env: TOXENV=py33
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: pypy
          env: TOXENV=pypy
        - python: 2.6
          env: TOXENV=py26 OPENSSL=0.9.8
          addons:
              apt:
                  sources:
                      - lucid
                  packages:
                      - libssl-dev/lucid
        - python: 2.7
          env: TOXENV=py27 OPENSSL=0.9.8
          addons:
              apt:
                  sources:
                      - lucid
                  packages:
                      - libssl-dev/lucid
        - python: 3.3
          env: TOXENV=py33 OPENSSL=0.9.8
          addons:
              apt:
                  sources:
                      - lucid
                  packages:
                      - libssl-dev/lucid
        - python: 3.4
          env: TOXENV=py34 OPENSSL=0.9.8
          addons:
              apt:
                  sources:
                      - lucid
                  packages:
                      - libssl-dev/lucid
        - python: 3.5
          env: TOXENV=py35 OPENSSL=0.9.8
          addons:
              apt:
                  sources:
                      - lucid
                  packages:
                      - libssl-dev/lucid
        - python: pypy
          env: TOXENV=pypy OPENSSL=0.9.8
          addons:
              apt:
                  sources:
                      - lucid
                  packages:
                      - libssl-dev/lucid
        - python: 2.7
          env: TOXENV=docs
          addons:
              apt:
                  packages:
                      - libenchant-dev
        - python: 2.7
          env: TOXENV=pep8
        - python: 3.4
          env: TOXENV=py3pep8
        - language: generic
          os: osx
          osx_image: xcode7
          env: TOXENV=py26 CRYPTOGRAPHY_OSX_NO_LINK_FLAGS=1
        - language: generic
          os: osx
          osx_image: xcode7
          env: TOXENV=py27 CRYPTOGRAPHY_OSX_NO_LINK_FLAGS=1
        - language: generic
          os: osx
          osx_image: xcode7
          env: TOXENV=py33 CRYPTOGRAPHY_OSX_NO_LINK_FLAGS=1
        - language: generic
          os: osx
          osx_image: xcode7
          env: TOXENV=py34 CRYPTOGRAPHY_OSX_NO_LINK_FLAGS=1
        - language: generic
          os: osx
          osx_image: xcode7
          env: TOXENV=py35 CRYPTOGRAPHY_OSX_NO_LINK_FLAGS=1
        - language: generic
          os: osx
          osx_image: xcode7
          env: TOXENV=pypy CRYPTOGRAPHY_OSX_NO_LINK_FLAGS=1
        - language: generic
          os: osx
          osx_image: xcode7
          env: TOXENV=py27 CRYPTOGRAPHY_OSX_NO_LINK_FLAGS=0
        - language: generic
          os: osx
          osx_image: xcode7
          env: TOXENV=py26 OPENSSL=0.9.8
        - language: generic
          os: osx
          osx_image: xcode7
          env: TOXENV=py27 OPENSSL=0.9.8
        - language: generic
          os: osx
          osx_image: xcode7
          env: TOXENV=py33 OPENSSL=0.9.8
        - language: generic
          os: osx
          osx_image: xcode7
          env: TOXENV=py34 OPENSSL=0.9.8
        - language: generic
          os: osx
          osx_image: xcode7
          env: TOXENV=py35 OPENSSL=0.9.8
        - language: generic
          os: osx
          osx_image: xcode7
          env: TOXENV=pypy OPENSSL=0.9.8
        - language: generic
          os: osx
          osx_image: xcode7
          env: TOXENV=docs

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

after_success:
    - ./.travis/upload_coverage.sh

notifications:
    irc:
        channels:
            - "irc.freenode.org#cryptography-dev"
        use_notice: true
        skip_join: true
    webhooks:
        - https://buildtimetrend.herokuapp.com/travis
