sudo: false

language: python

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/ossl/

matrix:
    include:
        - python: 2.6 # these are just to make travis's UI a bit prettier
          env: TOXENV=py26
        - python: 2.7
          env: TOXENV=py27
        - python: 3.3
          env: TOXENV=py33
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: pypy
          env: TOXENV=pypy-nocoverage PYPY_VERSION=2.6.1
        - python: pypy
          env: TOXENV=pypy PYPY_VERSION=4.0.1
        - python: pypy
          env: TOXENV=pypy PYPY_VERSION=5.4.1
        - python: 2.7
          env: TOXENV=py27 OPENSSL=1.0.0t
        - python: 3.5
          env: TOXENV=py35 OPENSSL=1.0.0t
        - python: 2.7
          env: TOXENV=py27 OPENSSL=1.1.0c
        - python: 3.5
          env: TOXENV=py35 OPENSSL=1.1.0c
        - python: 2.7
          env: TOXENV=docs
          addons:
              apt:
                  packages:
                      - libenchant-dev
        - python: 2.7
          env: TOXENV=pep8
        - python: 3.4
          env: TOXENV=py3pep8
        - language: generic
          os: osx
          # 8.1 is macOS 10.12.x
          # see: https://docs.travis-ci.com/user/osx-ci-environment/
          osx_image: xcode8.1
          env: TOXENV=py27 CRYPTOGRAPHY_OSX_NO_LINK_FLAGS=1
        - language: generic
          os: osx
          osx_image: xcode8.1
          env: TOXENV=py33 CRYPTOGRAPHY_OSX_NO_LINK_FLAGS=1
        - language: generic
          os: osx
          osx_image: xcode8.1
          env: TOXENV=py34 CRYPTOGRAPHY_OSX_NO_LINK_FLAGS=1
        - language: generic
          os: osx
          osx_image: xcode8.1
          env: TOXENV=py35 CRYPTOGRAPHY_OSX_NO_LINK_FLAGS=1
        - language: generic
          os: osx
          osx_image: xcode8.1
          env: TOXENV=pypy-nocoverage CRYPTOGRAPHY_OSX_NO_LINK_FLAGS=1 PYPY_VERSION=5.4.1
        - language: generic
          os: osx
          osx_image: xcode8.1
          env: TOXENV=py27 CRYPTOGRAPHY_OSX_NO_LINK_FLAGS=0
        - language: generic
          os: osx
          # 7.3 is OS X 10.11.x
          osx_image: xcode7.3
          env: TOXENV=py27 CRYPTOGRAPHY_OSX_NO_LINK_FLAGS=1
        - language: generic
          os: osx
          # 6.4 is OS X 10.10.x
          osx_image: xcode6.4
          env: TOXENV=py27 CRYPTOGRAPHY_OSX_NO_LINK_FLAGS=1
        - language: generic
          os: osx
          osx_image: xcode8.1
          env: TOXENV=docs CRYPTOGRAPHY_OSX_NO_LINK_FLAGS=1

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

after_success:
    - ./.travis/upload_coverage.sh

notifications:
    irc:
        channels:
            # This is set to a secure variable to prevent forks from notifying the
            # IRC channel whenever they fail a build. This can be removed when travis
            # implements https://github.com/travis-ci/travis-ci/issues/1094.
            # The value encrypted here was created via
            # travis encrypt "irc.freenode.org#cryptography-dev"
            - secure: "A93qvTOlwlMK5WoEvZQ5jQ8Z4Hd0JpeO53WYt8iIJ3s/L6AubkfiN7gwhThRtPnPx7DVMenoKRMlcRg76/ICvXEViVnGgXFjsypF0CzVcIay9pPdjpZjZHP735yLfX512RtxYEdEGwi5r25Z2CEFaydhhxNwfuMxGBtLUjusix4="
        use_notice: true
        skip_join: true
