sudo: false
dist: trusty

language: python

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/ossl-1/

# Only build master, the version branches (e.g. 1.7.x), and
# version tags (which are apparently considered branches by travis)
branches:
    only:
        - master
        - /\d+\.\d+\.x/
        - /\d+\.\d+(\.\d+)?/

matrix:
    include:
        # these are just to make travis's UI a bit prettier
        - python: 2.7
          env: TOXENV=py27
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: pypy-5.3
          env: TOXENV=pypy
        - python: pypy2.7-5.8.0
          env: TOXENV=pypy
        - python: pypy3.5-5.8.0
          env: TOXENV=pypy3-nocoverage
        - python: 2.7
          env: TOXENV=py27 OPENSSL=1.1.0g
        - python: 3.5
          env: TOXENV=py35 OPENSSL=1.1.0g
        - python: 2.7
          env: TOXENV=docs OPENSSL=1.1.0g
          addons:
              apt:
                  packages:
                      - libenchant-dev
        - python: 2.7
          env: TOXENV=pep8
        - python: 3.4
          env: TOXENV=py3pep8
        # - language: generic
        #   os: osx
        #   # 8.3 is macOS 10.12.x
        #   # see: https://docs.travis-ci.com/user/osx-ci-environment/
        #   osx_image: xcode8.3
        #   env: TOXENV=py27 CRYPTOGRAPHY_SUPPRESS_LINK_FLAGS=1
        # - language: generic
        #   os: osx
        #   osx_image: xcode8.3
        #   env: TOXENV=py34 CRYPTOGRAPHY_SUPPRESS_LINK_FLAGS=1
        # - language: generic
        #   os: osx
        #   osx_image: xcode8.3
        #   env: TOXENV=py35 CRYPTOGRAPHY_SUPPRESS_LINK_FLAGS=1
        # - language: generic
        #   os: osx
        #   osx_image: xcode8.3
        #   env: TOXENV=py36 CRYPTOGRAPHY_SUPPRESS_LINK_FLAGS=1
        # - language: generic
        #   os: osx
        #   osx_image: xcode8.3
        #   env: TOXENV=pypy-nocoverage CRYPTOGRAPHY_SUPPRESS_LINK_FLAGS=1 PYPY_VERSION=pypy2.7-5.8.0
        # - language: generic
        #   os: osx
        #   osx_image: xcode8.3
        #   env: TOXENV=py27 CRYPTOGRAPHY_SUPPRESS_LINK_FLAGS=0
        # - language: generic
        #   os: osx
        #   # 7.3 is OS X 10.11.x
        #   osx_image: xcode7.3
        #   env: TOXENV=py27 CRYPTOGRAPHY_SUPPRESS_LINK_FLAGS=1
        # - language: generic
        #   os: osx
        #   # 6.4 is OS X 10.10.x
        #   osx_image: xcode6.4
        #   env: TOXENV=py27 CRYPTOGRAPHY_SUPPRESS_LINK_FLAGS=1
        # - language: generic
        #   os: osx
        #   osx_image: xcode8.3
        #   env: TOXENV=docs CRYPTOGRAPHY_SUPPRESS_LINK_FLAGS=1

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

after_success:
    - ./.travis/upload_coverage.sh

notifications:
    irc:
        channels:
            # This is set to a secure variable to prevent forks from notifying the
            # IRC channel whenever they fail a build. This can be removed when travis
            # implements https://github.com/travis-ci/travis-ci/issues/1094.
            # The value encrypted here was created via
            # travis encrypt "irc.freenode.org#cryptography-dev"
            - secure: "A93qvTOlwlMK5WoEvZQ5jQ8Z4Hd0JpeO53WYt8iIJ3s/L6AubkfiN7gwhThRtPnPx7DVMenoKRMlcRg76/ICvXEViVnGgXFjsypF0CzVcIay9pPdjpZjZHP735yLfX512RtxYEdEGwi5r25Z2CEFaydhhxNwfuMxGBtLUjusix4="
        use_notice: true
        skip_join: true
