sudo: true
dist: focal

language: python

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/ossl-2/

# Only build master, the version branches (e.g. 1.7.x), and
# version tags (which are apparently considered branches by travis)
branches:
    only:
        - master
        - /\d+\.\d+\.x/
        - /\d+\.\d+(\.\d+)?/

matrix:
    include:
        - python: 3.8
          env: TOXENV=pep8,packaging
        # Setting 'python' is just to make travis's UI a bit prettier
        - python: 3.6
          env: TOXENV=py36
          # Travis lists available Pythons (including PyPy) by arch and distro here:
          # https://docs.travis-ci.com/user/languages/python/#python-versions
        - python: pypy2.7-7.3.1
          env: TOXENV=pypy-nocoverage
        - python: pypy3.6-7.3.1
          env: TOXENV=pypy3-nocoverage
        - python: 3.8
          env: TOXENV=py38 OPENSSL=1.0.2u
        - python: 2.7
          env: TOXENV=py27 OPENSSL=1.1.0l
        - python: 2.7
          env: TOXENV=py27-ssh OPENSSL=1.1.0l
        - python: 3.8
          env: TOXENV=py38 OPENSSL=1.1.0l
        - python: 2.7
          env: TOXENV=py27 OPENSSL=1.1.1g
        - python: 3.8
          env: TOXENV=py38 OPENSSL=1.1.1g
        - python: 3.8
          env: TOXENV=py38 OPENSSL=1.1.1g OPENSSL_CONFIG_FLAGS="no-engine no-rc2 no-srtp no-ct"
        - python: 3.8
          env: TOXENV=py38-ssh OPENSSL=1.1.1g
        - python: 3.8
          env: TOXENV=py38 LIBRESSL=2.9.2
        - python: 3.8
          env: TOXENV=py38 LIBRESSL=3.0.2
        - python: 3.8
          env: TOXENV=py38 LIBRESSL=3.1.3
        - python: 3.8
          env: TOXENV=py38 LIBRESSL=3.2.0

        - python: 2.7
          services: docker
          env: TOXENV=py27 DOCKER=pyca/cryptography-runner-centos7
        - python: 2.7
          services: docker
          env: TOXENV=py27 DOCKER=pyca/cryptography-runner-centos8
        - python: 3.6
          services: docker
          env: TOXENV=py36 DOCKER=pyca/cryptography-runner-centos8
        - python: 3.6
          services: docker
          env: TOXENV=py36 OPENSSL_FORCE_FIPS_MODE=1 DOCKER=pyca/cryptography-runner-centos8-fips
        - python: 2.7
          services: docker
          env: TOXENV=py27 DOCKER=pyca/cryptography-runner-stretch
        - python: 3.5
          services: docker
          env: TOXENV=py35 DOCKER=pyca/cryptography-runner-stretch
        - python: 3.7
          services: docker
          env: TOXENV=py37 DOCKER=pyca/cryptography-runner-buster
        - python: 3.8
          services: docker
          env: TOXENV=py38 DOCKER=pyca/cryptography-runner-bullseye
        - python: 3.8
          services: docker
          env: TOXENV=py38 DOCKER=pyca/cryptography-runner-sid
        - python: 3.6
          services: docker
          env: TOXENV=py36 DOCKER=pyca/cryptography-runner-ubuntu-bionic
        - python: 3.8
          services: docker
          env: TOXENV=py38 DOCKER=pyca/cryptography-runner-ubuntu-focal
        - python: 2.7
          services: docker
          env: TOXENV=py27 DOCKER=pyca/cryptography-runner-ubuntu-rolling
        - python: 3.8
          services: docker
          env: TOXENV=py38 DOCKER=pyca/cryptography-runner-ubuntu-rolling
        - python: 3.8
          services: docker
          env: TOXENV=py38-randomorder DOCKER=pyca/cryptography-runner-ubuntu-rolling
        - python: 3.8
          services: docker
          env: TOXENV=py38 DOCKER=pyca/cryptography-runner-fedora
        - python: 3.8
          services: docker
          env: TOXENV=py38 DOCKER=pyca/cryptography-runner-alpine:latest

        - python: 3.8
          env: TOXENV=docs OPENSSL=1.1.1g
          addons:
              apt:
                  packages:
                      - libenchant-dev
        - python: 3.8
          services: docker
          env: TOXENV=docs-linkcheck DOCKER=pyca/cryptography-runner-buster
          if: (branch = master AND type != pull_request) OR commit_message =~ /linkcheck/

        - python: 3.8
          env: DOWNSTREAM=pyopenssl
        - python: 3.7
          env: DOWNSTREAM=twisted OPENSSL=1.1.1g
        # Temporary disabled until
        # https://github.com/paramiko/paramiko/pull/1723 is merged
        # - python: 2.7
        #   env: DOWNSTREAM=paramiko
        - python: 3.8
          env: DOWNSTREAM=aws-encryption-sdk
        - python: 3.8
          # BOTO_CONFIG works around this boto issue on travis:
          # https://github.com/boto/boto/issues/3717
          env: DOWNSTREAM=dynamodb-encryption-sdk BOTO_CONFIG=/dev/null
        - python: 3.8
          env: DOWNSTREAM=certbot
        - python: 3.8
          env: DOWNSTREAM=certbot-josepy
        - python: 3.8
          env: DOWNSTREAM=urllib3
          # Tests hang when run under bionic/focal
          dist: xenial

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

after_success:
    - ./.travis/upload_coverage.sh

notifications:
    irc:
        channels:
            # This is set to a secure variable to prevent forks from notifying the
            # IRC channel whenever they fail a build. This can be removed when travis
            # implements https://github.com/travis-ci/travis-ci/issues/1094.
            # The value encrypted here was created via
            # travis encrypt "irc.freenode.org#cryptography-dev"
            - secure: "A93qvTOlwlMK5WoEvZQ5jQ8Z4Hd0JpeO53WYt8iIJ3s/L6AubkfiN7gwhThRtPnPx7DVMenoKRMlcRg76/ICvXEViVnGgXFjsypF0CzVcIay9pPdjpZjZHP735yLfX512RtxYEdEGwi5r25Z2CEFaydhhxNwfuMxGBtLUjusix4="
        use_notice: true
        skip_join: true
