trigger:
  branches:
    include:
      - "master"
      - "*.x"
  tags:
    include:
      - "*"

jobs:
- job: 'mac'
  pool:
    vmImage: $[variables.vmImage]
  strategy:
    matrix:
      Python27-macOS1013:
        python.version: '2.7'
        TOXENV: py27
        vmImage: 'macOS-10.13'
        MACOS_VERSION: '10.13'
      Python38-macOS1013:
        python.version: '3.8'
        TOXENV: py38
        vmImage: 'macOS-10.13'
        MACOS_VERSION: '10.13'
      Python27-macOS1014:
        python.version: '2.7'
        TOXENV: py27
        vmImage: 'macOS-10.14'
        MACOS_VERSION: '10.14'
      Python38-macOS1014:
        python.version: '3.8'
        TOXENV: py38
        vmImage: 'macOS-10.14'
        MACOS_VERSION: '10.14'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: brew update
    displayName: 'brew update'

  - script: brew install openssl@1.1
    displayName: 'Install OpenSSL'

  - script: pip install tox codecov
    displayName: 'Install tox & codecov'

  - script: git clone https://github.com/google/wycheproof
    displayName: 'Clone wycheproof'

  - script: |
      set -e
      set -x

      CRYPTOGRAPHY_SUPPRESS_LINK_FLAGS=1 \
        LDFLAGS="/usr/local/opt/openssl\\@1.1/lib/libcrypto.a /usr/local/opt/openssl\\@1.1/lib/libssl.a" \
        CFLAGS="-I/usr/local/opt/openssl\\@1.1/include -Werror -Wno-error=deprecated-declarations -Wno-error=incompatible-pointer-types-discards-qualifiers -Wno-error=unused-function -Wno-error=unused-command-line-argument -mmacosx-version-min=10.9" \
        tox -r --  --color=yes --wycheproof-root=wycheproof
    displayName: 'Run tests'

  - script: codecov -e MACOS_VERSION,AGENT_OS,TOXENV
    displayName: 'Submit coverage'
    condition: succeeded()
