[package]
name = "cryptography-rust"
version = "0.1.0"
authors = ["The cryptography developers <cryptography-dev@python.org>"]
edition = "2021"
publish = false
# This specifies the MSRV
rust-version = "1.56.0"

[dependencies]
once_cell = "1"
pyo3 = { version = "0.18" }
asn1 = { version = "0.14.0", default-features = false }
pem = "1.1"
ouroboros = "0.15"
openssl = "0.10.50"
openssl-sys = "0.9.85"
foreign-types-shared = "0.1"

[build-dependencies]
cc = "1.0.72"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[lib]
name = "cryptography_rust"
crate-type = ["cdylib"]

[profile.release]
lto = "thin"
overflow-checks = true
