[package]
name = "cryptography-cffi"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
pyo3 = { version = "0.22.1", features = ["abi3"] }
openssl-sys = "0.9.102"

[build-dependencies]
cc = "1.1.2"
