[package]
name = "verify-aes192gcmsiv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm-siv = "0.11.1"
aes = "0.8.1"
hex = "0.4.3"
