name: Auto-close stale issues
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: "write"
  pull-requests: "write"

jobs:
  auto-close:
    if: github.repository_owner == 'pyca'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8.0.0
        with:
          only-labels: waiting-on-reporter
          days-before-stale: 3
          days-before-close: 5
          stale-issue-message: "This issue has been waiting for a reporter response for 3 days. It will be auto-closed if no activity occurs in the next 5 days."
          close-issue-message: "This issue has not received a reporter response and has been auto-closed. If the issue is still relevant please leave a comment and we can reopen it."
          close-issue-reason: completed
