name: Bump BoringSSL version
permissions:
  contents: write
  pull-requests: write
  actions: write

on:
  workflow_dispatch:
  schedule:
    # Run daily
    - cron: "0 0 * * *"

jobs:
  bump:
    if: github.repository_owner == 'pyca'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - id: check-sha
        run: |
          SHA=$(git ls-remote https://boringssl.googlesource.com/boringssl HEAD | cut -f1)
          if ! grep -q "$SHA" .github/workflows/ci.yml; then
            echo "::set-output name=BORING_SHA::$SHA"
          fi
      - name: Update boring
        run: |
          set -xe
          CURRENT_DATE=$(date "+%b %d, %Y")
          sed -E -i "s/Latest commit on the master branch.*/Latest commit on the master branch, as of ${CURRENT_DATE}./" .github/workflows/ci.yml
          sed -E -i "s/TYPE: \"boringssl\", VERSION: \"[0-9a-f]{40}\"/TYPE: \"boringssl\", VERSION: \"${{ steps.check-sha.outputs.BORING_SHA }}\"/" .github/workflows/ci.yml
          git status
        if: steps.check-sha.outputs.BORING_SHA
      - uses: tibdex/github-app-token@586e1a624db6a5a4ac2c53daeeded60c5e3d50fe
        id: generate-token
        with:
          app_id: ${{ secrets.BORINGBOT_APP_ID }}
          private_key: ${{ secrets.BORINGBOT_PRIVATE_KEY }}
        if: steps.check-sha.outputs.BORING_SHA
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@f094b77505fb89581e68a1163fbd2fffece39da1
        with:
          commit-message: "Bump BoringSSL version to ${{ steps.check-sha.outputs.BORING_SHA }}"
          title: "Bump BoringSSL version to ${{ steps.check-sha.outputs.BORING_SHA }}"
          author: "BoringSSL Bot <pyca-boringbot@users.noreply.github.com>"
          token: ${{ steps.generate-token.outputs.token }}
        if: steps.check-sha.outputs.BORING_SHA
