name: linkcheck
on:
  pull_request:
    paths:
      - docs/conf.py
      - .github/workflows/linkcheck.yml
  push:
    branches:
      - main

permissions:
  contents: read

env:
  CARGO_INCREMENTAL: 0

jobs:
  docs-linkcheck:
    runs-on: ubuntu-latest
    name: "linkcheck"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          persist-credentials: false
      - name: Setup python
        id: setup-python
        uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v4.8.0
        with:
          python-version: 3.11
      - name: Cache rust and pip
        uses: ./.github/actions/cache
        timeout-minutes: 2
        with:
          # This creates the same key as the docs job (as long as they have the same
          # python version)
          key: 3.11-${{ steps.setup-python.outputs.python-version }}
      - run: python -m pip install -c ci-constraints-requirements.txt nox
      - name: Build nox environment
        run: |
            nox -v --install-only -s docs-linkcheck
        env:
          CARGO_TARGET_DIR: ${{ format('{0}/src/rust/target/', github.workspace) }}
      - name: linkcheck
        run: nox --no-install -s docs-linkcheck -- --color=yes
